---
title: "Correlated Numerical Data Analysis"
author: "Azmi"
date: "07/03/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(pacman)
p_load(haven, tidyverse, summarytools, broom)
```



# Tutorial 1

```{r}
myds <- read_dta("5.1.dta")
head(myds)
myds0 <- myds %>% 
  mutate_if(is.labelled, funs(as_factor(.)))
myds0 <- myds0 %>% 
  mutate(gender = factor(female, labels = c("male","female")),
         socialclass = factor(sclass, labels = c("manager_pro", "intermediate", "working", "unclassified")),
         schooltype = factor(schtype, labels = c("independent", "state")),
         urban = factor(schurban, labels = c("urban", "rural")),
         denom = factor(schdenom, labels = c("Catholic", "other"))) %>% 
  select(caseid, schoolid, score, cohort90, gender, socialclass, schooltype, urban, denom)
head(myds0)
```

```{r}
mydsgdenomurban <- myds0 %>% group_by(denom, urban)
ctable(mydsgdenomurban$socialclass, mydsgdenomurban$schooltype)
```

## Null model

```{r}
lmodnull <- lm(score ~ 1, data = myds0)
summary(lmodnull)
```

## Null Model MLE

```{r}
p_load(lme4)
```

```{r}
multlevmodnull <- lmer(score ~ 1 + (1|schoolid), data = myds0, REML = F)
summary(multlevmodnull)
tidy(multlevmodnull)
```

## Student level - cohort (Random Intercept Model)

```{r}
multlevmodcoh_RI <- lmer(score ~ cohort90 + (1|schoolid), data = myds0)
summary(multlevmodcoh_RI)
```

### Prediction - cohort

```{r}
scoreRI_pred <- augment(multlevmodcoh_RI)
scoreRI_pred
```

```{r}
ggplot(scoreRI_pred, aes(cohort90, .fitted, group = schoolid )) + geom_point() + geom_line() + theme_minimal()
```



## Student Level - cohort (Random Slope Model)

```{r}
multlevmodcoh_RS <- lmer(score ~ cohort90 + (1 + cohort90 | schoolid), data = myds0, REML = F)
summary(multlevmodcoh_RS)
```


### bobyqa optimize

```{r}
multlevmodcoh_RSb <- lmer(score ~ cohort90 + (1 + cohort90 | schoolid), data = myds0, control = lmerControl(optimizer = "bobyqa"), REML = F)
summary(multlevmodcoh_RSb)
```

### Prediction - with bobyqa optimize

```{r}
scoreRSb_pred <- augment(multlevmodcoh_RSb)
scoreRSb_pred
```

### Compare RI & RS

```{r}
anova(multlevmodcoh_RI, multlevmodcoh_RSb)
```

### plot

```{r}
ra_eff_rs <- ranef(multlevmodcoh_RSb, condVar = T)
head(ra_eff_rs)
```

```{r}
ra_eff_rs_scid <- ra_eff_rs$schoolid
ra_eff_rs_scid2 <- dplyr::rename(ra_eff_rs_scid,
                     rs_slope = cohort90,
                     rs_intercept = "(Intercept)")
ggplot(ra_eff_rs_scid2, aes(x = rs_intercept, y = rs_slope)) +
  geom_point() +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0) +
  theme_minimal()
```

